# Airbnb Amsterdam Data Cleaning & Preparation

This notebook documents the data cleaning and preprocessing steps applied to the Airbnb Amsterdam dataset.

The objective is to transform raw, unstructured data into a clean and consistent dataset suitable for:
- SQL-based analysis
- Power BI dashboard development

The process includes handling missing values, correcting data types, and selecting relevant features for analysis.

## Dataset Overview

The dataset consists of three main files:

- **Listings**: Detailed information about each property and host
- **Reviews**: Customer feedback and review history
- **Calendar**: Availability and pricing over time

Each dataset serves a different purpose and can be combined for deeper analysis.

In [1]:
import pandas as pd
import datetime

## # Load Data
The datasets includes:
- Listings: detailed property and host information
- Reviews: customer feedback
- Calendar: availability and pricing over time

The datasets are loaded into pandas DataFrames for inspection and preprocessing.

In [2]:
listings = pd.read_csv('/kaggle/input/datasets/josgomespinheironeto/raw-data/listings.csv')
listings.info()
listings.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10480 entries, 0 to 10479
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10480 non-null  int64
 1   listing_url                                   10480 non-null  object
 2   scrape_id                                     10480 non-null  int64
 3   last_scraped                                  10480 non-null  object
 4   source                                        10480 non-null  object
 5   name                                          10480 non-null  object
 6   description                                   10132 non-null  object
 7   neighborhood_overview                         5192 non-null   object
 8   picture_url                                   10480 non-null  object
 9   host_id                                       10480 non-null  int64
 10  host_url                                      10480 non-null  object
 11  host_name                                     10477 non-null  object
 12  host_since                                    10477 non-null  object
 13  host_location                                 9248 non-null   object
 14  host_about                                    5510 non-null   object
 15  host_response_time                            6683 non-null   object
 16  host_response_rate                            6683 non-null   object
 17  host_acceptance_rate                          8050 non-null   object
 18  host_is_superhost                             10365 non-null  object
 19  host_thumbnail_url                            10477 non-null  object
 20  host_picture_url                              10477 non-null  object
 21  host_neighbourhood                            2790 non-null   object
 22  host_listings_count                           10477 non-null  float64
 23  host_total_listings_count                     10477 non-null  float64
 24  host_verifications                            10477 non-null  object
 25  host_has_profile_pic                          10477 non-null  object
 26  host_identity_verified                        10477 non-null  object
 27  neighbourhood                                 5192 non-null   object
 28  neighbourhood_cleansed                        10480 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      10480 non-null  float64
 31  longitude                                     10480 non-null  float64
 32  property_type                                 10480 non-null  object
 33  room_type                                     10480 non-null  object
 34  accommodates                                  10480 non-null  int64
 35  bathrooms                                     5932 non-null   float64
 36  bathrooms_text                                10468 non-null  object
 37  bedrooms                                      10174 non-null  float64
 38  beds                                          5904 non-null   float64
 39  amenities                                     10480 non-null  object
 40  price                                         5874 non-null   object
 41  minimum_nights                                10480 non-null  int64
 42  maximum_nights                                10480 non-null  int64
 43  minimum_minimum_nights                        10476 non-null  float64
 44  maximum_minimum_nights                        10476 non-null  float64
 45  minimum_maximum_nights                        10476 non-null  float64
 46  maximum_maximum_nights                        10476 non-null  float64
 47  minimum_nights_avg_ntm                        10480 non-null  float64
 48  maximum_nights_avg_ntm                        10480 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              10137 non-null  object
 51  availability_30                               10480 non-null  int64
 52  availability_60                               10480 non-null  int64
 53  availability_90                               10480 non-null  int64
 54  availability_365                              10480 non-null  int64
 55  calendar_last_scraped                         10480 non-null  object
 56  number_of_reviews                             10480 non-null  int64
 57  number_of_reviews_ltm                         10480 non-null  int64
 58  number_of_reviews_l30d                        10480 non-null  int64
 59  availability_eoy                              10480 non-null  int64
 60  number_of_reviews_ly                          10480 non-null  int64
 61  estimated_occupancy_l365d                     10480 non-null  int64
 62  estimated_revenue_l365d                       5874 non-null   float64
 63  first_review                                  9383 non-null   object
 64  last_review                                   9383 non-null   object
 65  review_scores_rating                          9383 non-null   float64
 66  review_scores_accuracy                        9383 non-null   float64
 67  review_scores_cleanliness                     9382 non-null   float64
 68  review_scores_checkin                         9383 non-null   float64
 69  review_scores_communication                   9383 non-null   float64
 70  review_scores_location                        9383 non-null   float64
 71  review_scores_value                           9383 non-null   float64
 72  license                                       10361 non-null  object
 73  instant_bookable                              10480 non-null  object
 74  calculated_host_listings_count                10480 non-null  int64
 75  calculated_host_listings_count_entire_homes   10480 non-null  int64
 76  calculated_host_listings_count_private_rooms  10480 non-null  int64
 77  calculated_host_listings_count_shared_rooms   10480 non-null  int64
 78  reviews_per_month                             9383 non-null   float64
dtypes: float64(24), int64(20), object(35)
memory usage: 6.3+ MB

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,27886,https://www.airbnb.com/rooms/27886,20250911031321,2025-09-11,city scrape,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,"Central, quiet, safe, clean and beautiful.",https://a0.muscache.com/pictures/02c2da9d-660e...,97647,...,4.93,4.90,4.78,0363 974D 4986 7411 88D8,f,1,0,1,0,1.87
1,28871,https://www.airbnb.com/rooms/28871,20250911031321,2025-09-11,city scrape,Comfortable double room,Basic bedroom in the center of Amsterdam.,"Flower market , Leidseplein , Rembrantsplein",https://a0.muscache.com/pictures/160889/362340...,124245,...,4.94,4.93,4.83,0363 607B EA74 0BD8 2F6F,f,2,0,2,0,3.99
2,29051,https://www.airbnb.com/rooms/29051,20250911031321,2025-09-11,city scrape,Comfortable single / double room,This room can also be rented as a single or a ...,the street is quite lively especially on weeke...,https://a0.muscache.com/pictures/162009/bd6be2...,124245,...,4.92,4.87,4.79,0363 607B EA74 0BD8 2F6F,f,2,0,2,0,4.81
3,44391,https://www.airbnb.com/rooms/44391,20250911031321,2025-09-11,previous scrape,Quiet 2-bedroom Amsterdam city centre apartment,Guests greatly appreciate the unique location ...,The appartment is located in the city centre. ...,https://a0.muscache.com/pictures/97741545/3900...,194779,...,4.90,4.68,4.50,0363 E76E F06A C1DD 172C,f,1,1,0,0,0.23
4,48373,https://www.airbnb.com/rooms/48373,20250911031321,2025-09-11,previous scrape,Cozy family home in Amsterdam South,Charming modern apartment in the quiet and gre...,Apartment is located between Amsterdamse Bos a...,https://a0.muscache.com/pictures/miso/Hosting-...,220434,...,5.00,4.60,5.00,0363 4A2B A6AD 0196 F684,f,1,1,0,0,0.19

In [3]:
reviews = pd.read_csv('/kaggle/input/datasets/josgomespinheironeto/raw-data/reviews.csv')
reviews.info()
reviews.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501084 entries, 0 to 501083
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     501084 non-null  int64
 1   id             501084 non-null  int64
 2   date           501084 non-null  object
 3   reviewer_id    501084 non-null  int64
 4   reviewer_name  501083 non-null  object
 5   comments       501053 non-null  object
dtypes: int64(3), object(3)
memory usage: 22.9+ MB

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,839610,33387684,2015-05-27,32412055,Giuseppe,Nice time in nice place! Close to city center!...
1,839610,33865462,2015-06-01,33521461,Chi Kwan,The host is very friendly and helpful
2,839610,47062612,2015-09-15,25521258,Scott,"Michael, Jacob's son was the one to coordinate..."
3,839610,49847491,2015-10-06,32115691,Omer,Our stay was excelent. The appartment was clea...
4,839610,62280485,2016-02-13,16551781,Nina,it's very good! thanks! it's very beautiful al...

In [4]:
calendar = pd.read_csv('/kaggle/input/datasets/josgomespinheironeto/raw-data/calendar.csv')
calendar.info()
calendar.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3825200 entries, 0 to 3825199
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: float64(2), int64(3), object(2)
memory usage: 204.3+ MB

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,538723,2025-09-11,f,NaN,NaN,5,30
1,538723,2025-09-12,f,NaN,NaN,5,30
2,538723,2025-09-13,f,NaN,NaN,5,30
3,538723,2025-09-14,f,NaN,NaN,5,30
4,538723,2025-09-15,f,NaN,NaN,5,30

### Key Issues Identified

From the initial inspection, the following issues were observed:

- Price stored as string with currency symbols
- Percentage values stored as text
- Boolean values represented as 't'/'f'
- Presence of missing values in key columns
- Large number of irrelevant or redundant columns

## Data Cleaning
### Cleaning Listings Dataset

The original dataset contains over 70 columns, many of which are:
- Redundant
- Irrelevant to the analysis goals

To improve clarity and performance, a subset of key features was selected.

The selected features focus on:
- Pricing (price)
- Availability (availability_365, availability_30, instant_bookable)
- Host characteristics (host_is_superhost, host_response_rate)
- Property attributes (property_type, room_type, accommodates, bedrooms, beds, bathrooms)
- Location (neighbourhood_cleansed, latitude, longitude)
- Performance indicators (number_of_reviews, review_scores_rating)

In [5]:
columns_to_keep = [
    "id", "host_id",
    "neighbourhood_cleansed", "latitude", "longitude",
    "property_type", "room_type", "accommodates",
    "bedrooms", "beds", "bathrooms",
    "price",
    "availability_365", "availability_30",
    "number_of_reviews", "review_scores_rating",
    "host_is_superhost", "host_response_rate",
    "instant_bookable"
]

listings = listings[columns_to_keep]

### Cleaning Calendar Dataset

The calendar dataset provides daily availability and pricing information for each listing.

During inspection, it was observed that the `price` and `adjusted_price` columns contain only missing values.  
As a result, these fields were excluded from the analysis. `minimum_nights` and `maximum_nights` were also excluded due to holding no real value for the analysis.

The dataset was reduced to retain only relevant columns:
- `listing_id`
- `date`
- `available`

In [6]:
calendar = calendar[[
    "listing_id",
    "date",
    "available"
]]

### Cleaning Reviews Dataset

The reviews dataset contains individual customer feedback records.

For this project, only structured and relevant fields were retained:
- `listing_id`
- `date`
- `reviewer_id`

The `comments`, `reviewer_id`, and `reviewer_name` fields were excluded, as the analysis focuses on quantitative metrics rather than text-based sentiment and overall user analysis.

In [7]:
reviews = reviews[[
    "listing_id",
    "date"
]]

### Parsing Date Columns

Date columns in the datasets were converted to datetime64 format to ensure consistency and enable time-based operations.

This transformation allows:
- Proper sorting and filtering
- Time-based aggregations
- Compatibility with SQL and Power BI time functions

In [ ]:
reviews["date_parsed"] = pd.to_datetime(reviews["date"], format="ISO8601")
reviews = reviews[[
    "listing_id",
    "date_parsed"
]]

In [ ]:
calendar["date_parsed"] = pd.to_datetime(calendar["date"], format="ISO8601")
calendar = calendar[[
    "listing_id",
    "date_parsed",
    "available"
]]

### Handling Price Column

The `price` column is stored as a string with currency symbols (e.g., "$132.00"), which prevents numerical operations such as aggregation and comparison. To enable analysis, the column is converted into a numeric format.

In [ ]:
listings["price"] = (
    listings["price"]
    .str.replace(r"[$,]", "", regex=True)
)

listings.price = listings.price.astype("float64")

### Converting Boolean Columns

Some columns (e.g., `host_is_superhost`, `instant_bookable`) are stored as 't'/'f'. These are converted into proper boolean values to improve readability and compatibility with analytical tools such as SQL and Power BI.

In [ ]:
listings["host_is_superhost"] = listings["host_is_superhost"].map({
    "t": True,
    "f": False
})
listings.host_is_superhost = listings.host_is_superhost.astype("boolean")

In [ ]:
listings["instant_bookable"] = listings["instant_bookable"].map({
    "t": True,
    "f": False
})
listings.instant_bookable = listings.instant_bookable.astype("boolean")

In [ ]:
calendar["available"] = calendar["available"].map({
    "t": True,
    "f": False
})
calendar["available"] = calendar["available"].astype("boolean")

### Handling Missing Property Attributes

Some property-related columns, such as `beds` and `bathrooms`, contain missing values.

These values were preserved, as:
- They do not prevent overall analysis
- Removing them would reduce dataset size unnecessarily

The focus is on maintaining dataset integrity while avoiding unnecessary data loss.

In [ ]:
listings["bathrooms"] = listings["bathrooms"].fillna(listings["bathrooms"].median())
listings["beds"] = listings["beds"].fillna(listings["beds"].median())
listings["bedrooms"] = listings["bedrooms"].fillna(listings["bedrooms"].median())

### Converting Percentage Columns

Columns such as `host_response_rate` are stored as strings with percentage symbols (e.g., "100%"), which prevents numerical analysis. These values are converted into numeric format for proper aggregation and comparison.

In [ ]:
listings["host_response_rate"] = (
    listings["host_response_rate"]
    .str.replace("%", "", regex=False)
)
listings.host_response_rate = listings.host_response_rate.astype("float64")

### Removing Listings Without Price

Listings with missing price values were removed from the dataset. Since price is a central variable for this analysis, retaining these records would not contribute to meaningful insights and could distort aggregated metrics.

In [ ]:
listings = listings[listings["price"].notna()]

### Handling Price Outliers

The price distribution revealed extreme values (e.g., listings exceeding 80,000), which are not representative of the typical market. Such outliers can significantly distort averages and mislead analysis. To improve data reliability, extreme values were removed based on statistical thresholds.

In [ ]:
listings = listings[listings["price"] < 1000]

### Creating Derived Metric

An additional feature was created to support downstream analysis:

- **Occupancy Rate**: derived from availability data. It helps to calculate the listings availability throughout the year.

In [ ]:
listings["occupancy_rate"] = 1 - (listings["availability_365"] / 365)

## Final Dataset Overview

The cleaned dataset contains:
- Listings (19 columns & 5.816 rows)
- Calendar (3 columns & 3.825.200 rows)
- Reviews (2 columns & 501.084 rows)
It is now ready for SQL modeling and Power BI visualization.

In [ ]:
listings.to_csv("listings.csv", index=False)
calendar.to_csv("calendar.csv", index=False)
reviews.to_csv("reviews.csv", index=False)

## Next Steps

The cleaned dataset is exported and used for further analysis:

- SQL queries are applied to explore relationships and aggregate metrics
- Power BI is used to build interactive dashboards and extract business insights

This notebook serves as the foundation for the full data analysis workflow.